### ISSUE TITLE
Mobilenetv2 demo error

### ISSUE THREAD

**Issue by GotG** [david8862/tf-keras-deeplabv3p-model-set#1]
Hello

When attempting demo with mobilenetv2:
 `python deeplab.py --model_type=mobilenetv2 --weights_path=/weights/deeplabv3_mobilenetv2_tf_dim_ordering_tf_kernels.h5 --classes_path=configs/voc_classes.txt --output_stride=16 --image`

I get the following error:

`backbone layers number: 148
ValueError('You are trying to load a weight file containing 109 layers into a model with 131 layers.',)
Traceback (most recent call last):
  File "deeplab.py", line 275, in <module>
    deeplab = DeepLab(**vars(args))
  File "deeplab.py", line 60, in __init__
    self.deeplab_model = self._generate_model()
  File "deeplab.py", line 81, in _generate_model
    return deeplab_model
UnboundLocalError: local variable 'deeplab_model' referenced before assignment`

Thanks!

**Comment by david8862** [comment]
@GotG  sorry for response delay. Which model file do you use, is it downloaded from the release link?

**Comment by GotG** [comment]
no probs. yes, the one from the link.
deeplabv3_mobilenetv2_tf_dim_ordering_tf_kernels.h5

**Comment by david8862** [comment]
Is it from https://github.com/david8862/tf-keras-deeplabv3p-model-set/releases/download/1.0.0/deeplabv3p_mobilenetv2_lite_512_os16_voc.tar.gz? If true then looks quite weired. Could you provide the original test image? I can try to verify on my testbed
